### ISSUE TITLE
lessThanOrEqual not working correctly?

### ISSUE THREAD

**Issue by envision** [mathiasverraes/money#106] opened 2015-09-15 18:54 UTC
Consider this output:

checking if this value: 15367555 is less than 0
it is less!

For this code:

	echo "checking if this value: ".$value->getAmount()." is less than ".Money::EUR(0)->getAmount();

	if ($value->lessThanOrEqual(Money::EUR(0))) {
		echo "<br> it is less!";
	} else {
		echo "<br> no its not";
	}
	die();

**Comment by sagikazarmark** [comment] 2016-01-12 08:37
Duplicate of #99

**Closed by sagikazarmark** 2016-01-12 08:37 UTC
